const demo={
    "OSEL DEVICES LIMITED": "OSELDEVICE.NS",
    "PANASONIC ENERGY INDIA COMPANY LIMITED": "PANAENERG.NS",
    "AVAILABLE FINANCE LIMITED": "AVAILFC.NS",
    "GEM ENVIRO MANAGEMENT LIMITED": "GEMENVIRO.NS",
    "QUINT DIGITAL LIMITED": "QUINT.NS",
    "TRIDENT LIFELINE LIMITED": "TLL.NS",
    "COCHIN MINERALS & RUTILE LIMITED": "COCHINM.NS",
    "WOODSVILLA. LIMITED": "WOODSVILA.NS",
}

module.exports={demo};