const { fetchIndexData } = require("../services/yaahoFinanceService");
const db = require("../db_conig/db");
const indices=require("./All_Com");

// index symobls of sotck market
// const indices = {
//   RelianceIndustries: "RELIANCE.NS",
//   AdaniEnterprises: "ADANIENT.NS",
//   AdaniPorts: "ADANIPORTS.NS",
//   ApolloHospitals: "APOLLOHOSP.NS",
//   AsianPaints: "ASIANPAINT.NS",
//   AxisBank: "AXISBANK.NS",
//   BajajAuto: "BAJAJ-AUTO.NS",
//   BajajFinance: "BAJFINANCE.NS",
//   BajajFinserv: "BAJAJFINSV.NS",
//   BharatElectronics: "BEL.NS",
//   BharatPetroleum: "BPCL.NS",
//   BhartiAirtel: "BHARTIARTL.NS",
//   BritanniaIndustries: "BRITANNIA.NS",
//   Cipla: "CIPLA.NS",
//   CoalIndia: "COALINDIA.NS",
//   DrReddys: "DRREDDY.NS",
//   EicherMotors: "EICHERMOT.NS",
//   GrasimIndustries: "GRASIM.NS",
//   HCLTech: "HCLTECH.NS",
//   HDFCBank: "HDFCBANK.NS",
//   HDFCLife: "HDFCLIFE.NS",
//   HeroMotoCorp: "HEROMOTOCO.NS",
//   HindalcoIndustries: "HINDALCO.NS",
//   HindustanUnilever: "HINDUNILVR.NS",
//   ICICIBank: "ICICIBANK.NS",
//   IndusIndBank: "INDUSINDBK.NS",
//   Infosys: "INFY.NS",
//   ITC: "ITC.NS",
//   JSWSteel: "JSWSTEEL.NS",
//   KotakMahindraBank: "KOTAKBANK.NS",
//   LarsenToubro: "LT.NS",
//   MahindraMahindra: "M&M.NS",
//   MarutiSuzuki: "MARUTI.NS",
//   NestleIndia: "NESTLEIND.NS",
//   NTPC: "NTPC.NS",
//   ONGC: "ONGC.NS",
//   PowerGrid: "POWERGRID.NS",
//   SBILife: "SBILIFE.NS",
//   ShriramFinance: "SHRIRAMFIN.NS",
//   StateBankOfIndia: "SBIN.NS",
//   SunPharma: "SUNPHARMA.NS",
//   TCS: "TCS.NS",
//   TataConsumer: "TATACONSUM.NS",
//   TataMotors: "TATAMOTORS.NS",
//   TataSteel: "TATASTEEL.NS",
//   TechMahindra: "TECHM.NS",
//   Titan: "TITAN.NS",
//   Trent: "TRENT.NS",
//   UltraTechCement: "ULTRACEMCO.NS",
//   Wipro: "WIPRO.NS", // Correct NSE symbol

// };

// const indices = {
//   "360 ONE WAM Ltd.": "360ONE.NS",
//   "3M India Ltd.": "3MINDIA.NS",
//   "ABB India Ltd.": "ABB.NS",
//   "ACC Ltd.": "ACC.NS",
//   "AIA Engineering Ltd.": "AIAENG.NS",
//   "APL Apollo Tubes Ltd.": "APLAPOLLO.NS",
//   "AU Small Finance Bank Ltd.": "AUBANK.NS",
//   "Aadhar Housing Finance Ltd.": "AADHARHFC.NS",
//   "Aarti Industries Ltd.": "AARTIIND.NS",
//   "Aavas Financiers Ltd.": "AAVAS.NS",
//   "Abbott India Ltd.": "ABBOTINDIA.NS",
//   "Action Construction Equipment Ltd.": "ACE.NS",
//   "Adani Energy Solutions Ltd.": "ADANIENSOL.NS",
//   "Adani Enterprises Ltd.": "ADANIENT.NS",
//   "Adani Green Energy Ltd.": "ADANIGREEN.NS",
//   "Adani Ports and Special Economic Zone Ltd.": "ADANIPORTS.NS",
//   "Adani Power Ltd.": "ADANIPOWER.NS",
//   "Adani Total Gas Ltd.": "ATGL.NS",
//   "Adani Wilmar Ltd.": "AWL.NS",
//   "Aditya Birla Capital Ltd.": "ABCAPITAL.NS",
//   "Aditya Birla Fashion and Retail Ltd.": "ABFRL.NS",
//   "Aditya Birla Real Estate Ltd.": "ABREL.NS",
//   "Aditya Birla Sun Life AMC Ltd.": "ABSLAMC.NS",
//   "Aegis Logistics Ltd.": "AEGISLOG.NS",
//   "Affle (India) Ltd.": "AFFLE.NS",
//   "Ajanta Pharmaceuticals Ltd.": "AJANTPHARM.NS",
//   "Akums Drugs and Pharmaceuticals Ltd.": "AKUMS.NS",
//   "Alembic Pharmaceuticals Ltd.": "APLLTD.NS",
//   "Alkem Laboratories Ltd.": "ALKEM.NS",
//   "Alkyl Amines Chemicals Ltd.": "ALKYLAMINE.NS",
//   "Alok Industries Ltd.": "ALOKINDS.NS",
//   "Amara Raja Energy & Mobility Ltd.": "ARE&M.NS",
//   "Amber Enterprises India Ltd.": "AMBER.NS",
//   "Ambuja Cements Ltd.": "AMBUJACEM.NS",
//   "Anand Rathi Wealth Ltd.": "ANANDRATHI.NS",
//   "Anant Raj Ltd.": "ANANTRAJ.NS",
//   "Angel One Ltd.": "ANGELONE.NS",
//   "Apar Industries Ltd.": "APARINDS.NS",
//   "Apollo Hospitals Enterprise Ltd.": "APOLLOHOSP.NS",
//   "Apollo Tyres Ltd.": "APOLLOTYRE.NS",
//   "Aptus Value Housing Finance India Ltd.": "APTUS.NS",
//   "Archean Chemical Industries Ltd.": "ACI.NS",
//   "Asahi India Glass Ltd.": "ASAHIINDIA.NS",
//   "Ashok Leyland Ltd.": "ASHOKLEY.NS",
//   "Asian Paints Ltd.": "ASIANPAINT.NS",
//   "Aster DM Healthcare Ltd.": "ASTERDM.NS",
//   "AstraZenca Pharma India Ltd.": "ASTRAZEN.NS",
//   "Astral Ltd.": "ASTRAL.NS",
//   "Atul Ltd.": "ATUL.NS",
//   "Aurobindo Pharma Ltd.": "AUROPHARMA.NS",
//   "Avanti Feeds Ltd.": "AVANTIFEED.NS",
//   "Avenue Supermarts Ltd.": "DMART.NS",
//   "Axis Bank Ltd.": "AXISBANK.NS",
//   "BASF India Ltd.": "BASF.NS",
//   "BEML Ltd.": "BEML.NS",
//   "BLS International Services Ltd.": "BLS.NS",
//   "BSE Ltd.": "BSE.NS",
//   "Bajaj Auto Ltd.": "BAJAJ-AUTO.NS",
//   "Bajaj Finance Ltd.": "BAJFINANCE.NS",
//   "Bajaj Finserv Ltd.": "BAJAJFINSV.NS",
//   "Bajaj Holdings & Investment Ltd.": "BAJAJHLDNG.NS",
//   "Balaji Amines Ltd.": "BALAMINES.NS",
//   "Balkrishna Industries Ltd.": "BALKRISIND.NS",
//   "Balrampur Chini Mills Ltd.": "BALRAMCHIN.NS",
//   "Bandhan Bank Ltd.": "BANDHANBNK.NS",
//   "Bank of Baroda": "BANKBARODA.NS",
//   "Bank of India": "BANKINDIA.NS",
//   "Bank of Maharashtra": "MAHABANK.NS",
//   "Bata India Ltd.": "BATAINDIA.NS",
//   "Bayer Cropscience Ltd.": "BAYERCROP.NS",
//   "Berger Paints India Ltd.": "BERGEPAINT.NS",
//   "Bharat Dynamics Ltd.": "BDL.NS",
//   "Bharat Electronics Ltd.": "BEL.NS",
//   "Bharat Forge Ltd.": "BHARATFORG.NS",
//   "Bharat Heavy Electricals Ltd.": "BHEL.NS",
//   "Bharat Petroleum Corporation Ltd.": "BPCL.NS",
//   "Bharti Airtel Ltd.": "BHARTIARTL.NS",
//   "Bharti Hexacom Ltd.": "BHARTIHEXA.NS",
//   "Bikaji Foods International Ltd.": "BIKAJI.NS",
//   "Biocon Ltd.": "BIOCON.NS",
//   "Birla Corporation Ltd.": "BIRLACORPN.NS",
//   "Birlasoft Ltd.": "BSOFT.NS",
//   "Blue Dart Express Ltd.": "BLUEDART.NS",
//   "Blue Star Ltd.": "BLUESTARCO.NS",
//   "Bombay Burmah Trading Corporation Ltd.": "BBTC.NS",
//   "Bosch Ltd.": "BOSCHLTD.NS",
//   "Brigade Enterprises Ltd.": "BRIGADE.NS",
//   "Britannia Industries Ltd.": "BRITANNIA.NS",
//   "C.E. Info Systems Ltd.": "MAPMYINDIA.NS",
//   "CCL Products (I) Ltd.": "CCL.NS",
//   "CESC Ltd.": "CESC.NS",
//   "CG Power and Industrial Solutions Ltd.": "CGPOWER.NS",
//   "CIE Automotive India Ltd.": "CIEINDIA.NS",
//   "CRISIL Ltd.": "CRISIL.NS",
//   "Campus Activewear Ltd.": "CAMPUS.NS",
//   "Can Fin Homes Ltd.": "CANFINHOME.NS",
//   "Canara Bank": "CANBK.NS",
//   "Caplin Point Laboratories Ltd.": "CAPLIPOINT.NS",
//   "Capri Global Capital Ltd.": "CGCL.NS",
//   "Carborundum Universal Ltd.": "CARBORUNIV.NS",
//   "Castrol India Ltd.": "CASTROLIND.NS",
//   "Ceat Ltd.": "CEATLTD.NS",
//   "Cello World Ltd.": "CELLO.NS",
//   "Central Bank of India": "CENTRALBK.NS",
//   "Central Depository Services (India) Ltd.": "CDSL.NS",
//   "Century Plyboards (India) Ltd.": "CENTURYPLY.NS",
//   "Cera Sanitaryware Ltd": "CERA.NS",
//   "Chalet Hotels Ltd.": "CHALET.NS",
//   "Chambal Fertilizers & Chemicals Ltd.": "CHAMBLFERT.NS",
//   "Chemplast Sanmar Ltd.": "CHEMPLASTS.NS",
//   "Chennai Petroleum Corporation Ltd.": "CHENNPETRO.NS",
//   "Cholamandalam Financial Holdings Ltd.": "CHOLAHLDNG.NS",
//   "Cholamandalam Investment and Finance Company Ltd.": "CHOLAFIN.NS",
//   "Cipla Ltd.": "CIPLA.NS",
//   "City Union Bank Ltd.": "CUB.NS",
//   "Clean Science and Technology Ltd.": "CLEAN.NS",
//   "Coal India Ltd.": "COALINDIA.NS",
//   "Cochin Shipyard Ltd.": "COCHINSHIP.NS",
//   "Coforge Ltd.": "COFORGE.NS",
//   "Colgate Palmolive (India) Ltd.": "COLPAL.NS",
//   "Computer Age Management Services Ltd.": "CAMS.NS",
//   "Concord Biotech Ltd.": "CONCORDBIO.NS",
//   "Container Corporation of India Ltd.": "CONCOR.NS",
//   "Coromandel International Ltd.": "COROMANDEL.NS",
//   "Craftsman Automation Ltd.": "CRAFTSMAN.NS",
//   "CreditAccess Grameen Ltd.": "CREDITACC.NS",
//   "Crompton Greaves Consumer Electricals Ltd.": "CROMPTON.NS",
//   "Cummins India Ltd.": "CUMMINSIND.NS",
//   "Cyient Ltd.": "CYIENT.NS",
//   "DLF Ltd.": "DLF.NS",
//   "DOMS Industries Ltd.": "DOMS.NS",
//   "Dabur India Ltd.": "DABUR.NS",
//   "Dalmia Bharat Ltd.": "DALBHARAT.NS",
//   "Data Patterns (India) Ltd.": "DATAPATTNS.NS",
//   "Deepak Fertilisers & Petrochemicals Corp. Ltd.": "DEEPAKFERT.NS",
//   "Deepak Nitrite Ltd.": "DEEPAKNTR.NS",
//   "Delhivery Ltd.": "DELHIVERY.NS",
//   "Devyani International Ltd.": "DEVYANI.NS",
//   "Divi's Laboratories Ltd.": "DIVISLAB.NS",
//   "Dixon Technologies (India) Ltd.": "DIXON.NS",
//   "Dr. Lal Path Labs Ltd.": "LALPATHLAB.NS",
//   "Dr. Reddy's Laboratories Ltd.": "DRREDDY.NS",
//   "E.I.D. Parry (India) Ltd.": "EIDPARRY.NS",
//   "EIH Ltd.": "EIHOTEL.NS",
//   "Easy Trip Planners Ltd.": "EASEMYTRIP.NS",
//   "Eicher Motors Ltd.": "EICHERMOT.NS",
//   "Elecon Engineering Co. Ltd.": "ELECON.NS",
//   "Elgi Equipments Ltd.": "ELGIEQUIP.NS",
//   "Emami Ltd.": "EMAMILTD.NS",
//   "Emcure Pharmaceuticals Ltd.": "EMCURE.NS",
//   "Endurance Technologies Ltd.": "ENDURANCE.NS",
//   "Engineers India Ltd.": "ENGINERSIN.NS",
//   "Equitas Small Finance Bank Ltd.": "EQUITASBNK.NS",
//   "Eris Lifesciences Ltd.": "ERIS.NS",
//   "Escorts Kubota Ltd.": "ESCORTS.NS",
//   "Exide Industries Ltd.": "EXIDEIND.NS",
//   "FSN E-Commerce Ventures Ltd.": "NYKAA.NS",
//   "Federal Bank Ltd.": "FEDERALBNK.NS",
//   "Fertilisers and Chemicals Travancore Ltd.": "FACT.NS",
//   "Fine Organic Industries Ltd.": "FINEORG.NS",
//   "Finolex Cables Ltd.": "FINCABLES.NS",
//   "Finolex Industries Ltd.": "FINPIPE.NS",
//   "Firstsource Solutions Ltd.": "FSL.NS",
//   "Five-Star Business Finance Ltd.": "FIVESTAR.NS",
//   "Fortis Healthcare Ltd.": "FORTIS.NS",
//   "G R Infraprojects Ltd.": "GRINFRA.NS",
//   "GAIL (India) Ltd.": "GAIL.NS",
//   "GE Vernova T&D India Ltd.": "GVT&D.NS",
//   "GMR Airports Ltd.": "GMRAIRPORT.NS",
//   "Garden Reach Shipbuilders & Engineers Ltd.": "GRSE.NS",
//   "General Insurance Corporation of India": "GICRE.NS",
//   "Gillette India Ltd.": "GILLETTE.NS",
//   "Gland Pharma Ltd.": "GLAND.NS",
//   "Glaxosmithkline Pharmaceuticals Ltd.": "GLAXO.NS",
//   "Glenmark Pharmaceuticals Ltd.": "GLENMARK.NS",
//   "Global Health Ltd.": "MEDANTA.NS",
//   "Go Digit General Insurance Ltd.": "GODIGIT.NS",
//   "Godawari Power & Ispat Ltd.": "GPIL.NS",
//   "Godfrey Phillips India Ltd.": "GODFRYPHLP.NS",
//   "Godrej Agrovet Ltd.": "GODREJAGRO.NS",
//   "Godrej Consumer Products Ltd.": "GODREJCP.NS",
//   "Godrej Industries Ltd.": "GODREJIND.NS",
//   "Godrej Properties Ltd.": "GODREJPROP.NS",
//   "Granules India Ltd.": "GRANULES.NS",
//   "Graphite India Ltd.": "GRAPHITE.NS",
//   "Grasim Industries Ltd.": "GRASIM.NS",
//   "Great Eastern Shipping Co. Ltd.": "GESHIP.NS",
//   "Grindwell Norton Ltd.": "GRINDWELL.NS",
//   "Gujarat Ambuja Exports Ltd.": "GAEL.NS",
//   "Gujarat Fluorochemicals Ltd.": "FLUOROCHEM.NS",
//   "Gujarat Gas Ltd.": "GUJGASLTD.NS",
//   "Gujarat Mineral Development Corporation Ltd.": "GMDCLTD.NS",
//   "Gujarat Narmada Valley Fertilizers and Chemicals Ltd.": "GNFC.NS",
//   "Gujarat Pipavav Port Ltd.": "GPPL.NS",
//   "Gujarat State Fertilizers & Chemicals Ltd.": "GSFC.NS",
//   "Gujarat State Petronet Ltd.": "GSPL.NS",
//   "H.E.G. Ltd.": "HEG.NS",
//   "HBL Engineering Ltd.": "HBLENGINE.NS",
//   "HCL Technologies Ltd.": "HCLTECH.NS",
//   "HDFC Asset Management Company Ltd.": "HDFCAMC.NS",
//   "HDFC Bank Ltd.": "HDFCBANK.NS",
//   "HDFC Life Insurance Company Ltd.": "HDFCLIFE.NS",
//   "HFCL Ltd.": "HFCL.NS",
//   "Happiest Minds Technologies Ltd.": "HAPPSTMNDS.NS",
//   "Havells India Ltd.": "HAVELLS.NS",
//   "Hero MotoCorp Ltd.": "HEROMOTOCO.NS",
//   "Himadri Speciality Chemical Ltd.": "HSCL.NS",
//   "Hindalco Industries Ltd.": "HINDALCO.NS",
//   "Hindustan Aeronautics Ltd.": "HAL.NS",
//   "Hindustan Copper Ltd.": "HINDCOPPER.NS",
//   "Hindustan Petroleum Corporation Ltd.": "HINDPETRO.NS",
//   "Hindustan Unilever Ltd.": "HINDUNILVR.NS",
//   "Hindustan Zinc Ltd.": "HINDZINC.NS",
//   "Hitachi Energy India Ltd.": "POWERINDIA.NS",
//   "Home First Finance Company India Ltd.": "HOMEFIRST.NS",
//   "Honasa Consumer Ltd.": "HONASA.NS",
//   "Honeywell Automation India Ltd.": "HONAUT.NS",
//   "Housing & Urban Development Corporation Ltd.": "HUDCO.NS",
//   "ICICI Bank Ltd.": "ICICIBANK.NS",
//   "ICICI Lombard General Insurance Company Ltd.": "ICICIGI.NS",
//   "ICICI Prudential Life Insurance Company Ltd.": "ICICIPRULI.NS",
//   "ICICI Securities Ltd.": "ISEC.NS",
//   "IDBI Bank Ltd.": "IDBI.NS",
//   "IDFC First Bank Ltd.": "IDFCFIRSTB.NS",
//   "IFCI Ltd.": "IFCI.NS",
//   "IIFL Finance Ltd.": "IIFL.NS",
//   "INOX India Ltd.": "INOXINDIA.NS",
//   "IRB Infrastructure Developers Ltd.": "IRB.NS",
//   "IRCON International Ltd.": "IRCON.NS",
//   "ITC Ltd.": "ITC.NS",
//   "ITI Ltd.": "ITI.NS",
//   "Indegene Ltd.": "INDGN.NS",
//   "India Cements Ltd.": "INDIACEM.NS",
//   "Indiamart Intermesh Ltd.": "INDIAMART.NS",
//   "Indian Bank": "INDIANB.NS",
//   "Indian Energy Exchange Ltd.": "IEX.NS",
//   "Indian Hotels Co. Ltd.": "INDHOTEL.NS",
//   "Indian Oil Corporation Ltd.": "IOC.NS",
//   "Indian Overseas Bank": "IOB.NS",
//   "Indian Railway Catering And Tourism Corporation Ltd.": "IRCTC.NS",
//   "Indian Railway Finance Corporation Ltd.": "IRFC.NS",
//   "Indian Renewable Energy Development Agency Ltd.": "IREDA.NS",
//   "Indraprastha Gas Ltd.": "IGL.NS",
//   "Indus Towers Ltd.": "INDUSTOWER.NS",
//   "IndusInd Bank Ltd.": "INDUSINDBK.NS",
//   "Info Edge (India) Ltd.": "NAUKRI.NS",
//   "Infosys Ltd.": "INFY.NS",
//   "Inox Wind Ltd.": "INOXWIND.NS",
//   "Intellect Design Arena Ltd.": "INTELLECT.NS",
//   "InterGlobe Aviation Ltd.": "INDIGO.NS",
//   "Ipca Laboratories Ltd.": "IPCALAB.NS",
//   "J.B. Chemicals & Pharmaceuticals Ltd.": "JBCHEPHARM.NS",
//   "J.K. Cement Ltd.": "JKCEMENT.NS",
//   "JBM Auto Ltd.": "JBMA.NS",
//   "JK Lakshmi Cement Ltd.": "JKLAKSHMI.NS",
//   "JK Tyre & Industries Ltd.": "JKTYRE.NS",
//   "JM Financial Ltd.": "JMFINANCIL.NS",
//   "JSW Energy Ltd.": "JSWENERGY.NS",
//   "JSW Infrastructure Ltd.": "JSWINFRA.NS",
//   "JSW Steel Ltd.": "JSWSTEEL.NS",
//   "Jaiprakash Power Ventures Ltd.": "JPPOWER.NS",
//   "Jammu & Kashmir Bank Ltd.": "J&KBANK.NS",
//   "Jindal Saw Ltd.": "JINDALSAW.NS",
//   "Jindal Stainless Ltd.": "JSL.NS",
//   "Jindal Steel & Power Ltd.": "JINDALSTEL.NS",
//   "Jio Financial Services Ltd.": "JIOFIN.NS",
//   "Jubilant Foodworks Ltd.": "JUBLFOOD.NS",
//   "Jubilant Ingrevia Ltd.": "JUBLINGREA.NS",
//   "Jubilant Pharmova Ltd.": "JUBLPHARMA.NS",
//   "Jupiter Wagons Ltd.": "JWL.NS",
//   "Justdial Ltd.": "JUSTDIAL.NS",
//   "Jyothy Labs Ltd.": "JYOTHYLAB.NS",
//   "Jyoti CNC Automation Ltd.": "JYOTICNC.NS",
//   "K.P.R. Mill Ltd.": "KPRMILL.NS",
//   "KEI Industries Ltd.": "KEI.NS",
//   "KNR Constructions Ltd.": "KNRCON.NS",
//   "KPIT Technologies Ltd.": "KPITTECH.NS",
//   "KSB Ltd.": "KSB.NS",
//   "Kajaria Ceramics Ltd.": "KAJARIACER.NS",
//   "Kalpataru Projects International Ltd.": "KPIL.NS",
//   "Kalyan Jewellers India Ltd.": "KALYANKJIL.NS",
//   "Kansai Nerolac Paints Ltd.": "KANSAINER.NS",
//   "Karur Vysya Bank Ltd.": "KARURVYSYA.NS",
//   "Kaynes Technology India Ltd.": "KAYNES.NS",
//   "Kec International Ltd.": "KEC.NS",
//   "Kfin Technologies Ltd.": "KFINTECH.NS",
//   "Kirloskar Brothers Ltd.": "KIRLOSBROS.NS",
//   "Kirloskar Oil Eng Ltd.": "KIRLOSENG.NS",
//   "Kotak Mahindra Bank Ltd.": "KOTAKBANK.NS",
//   "Krishna Institute of Medical Sciences Ltd.": "KIMS.NS",
//   "L&T Finance Ltd.": "LTF.NS",
//   "L&T Technology Services Ltd.": "LTTS.NS",
//   "LIC Housing Finance Ltd.": "LICHSGFIN.NS",
//   "LTIMindtree Ltd.": "LTIM.NS",
//   "Larsen & Toubro Ltd.": "LT.NS",
//   "Latent View Analytics Ltd.": "LATENTVIEW.NS",
//   "Laurus Labs Ltd.": "LAURUSLABS.NS",
//   "Lemon Tree Hotels Ltd.": "LEMONTREE.NS",
//   "Life Insurance Corporation of India": "LICI.NS",
//   "Linde India Ltd.": "LINDEINDIA.NS",
//   "Lloyds Metals And Energy Ltd.": "LLOYDSME.NS",
//   "Lupin Ltd.": "LUPIN.NS",
//   "MMTC Ltd.": "MMTC.NS",
//   "MRF Ltd.": "MRF.NS",
//   "Macrotech Developers Ltd.": "LODHA.NS",
//   "Mahanagar Gas Ltd.": "MGL.NS",
//   "Maharashtra Seamless Ltd.": "MAHSEAMLES.NS",
//   "Mahindra & Mahindra Financial Services Ltd.": "M&MFIN.NS",
//   "Mahindra & Mahindra Ltd.": "M&M.NS",
//   "Mahindra Lifespace Developers Ltd.": "MAHLIFE.NS",
//   "Manappuram Finance Ltd.": "MANAPPURAM.NS",
//   "Mangalore Refinery & Petrochemicals Ltd.": "MRPL.NS",
//   "Mankind Pharma Ltd.": "MANKIND.NS",
//   "Marico Ltd.": "MARICO.NS",
//   "Maruti Suzuki India Ltd.": "MARUTI.NS",
//   "Mastek Ltd.": "MASTEK.NS",
//   "Max Financial Services Ltd.": "MFSL.NS",
//   "Max Healthcare Institute Ltd.": "MAXHEALTH.NS",
//   "Mazagoan Dock Shipbuilders Ltd.": "MAZDOCK.NS",
//   "Metro Brands Ltd.": "METROBRAND.NS",
//   "Metropolis Healthcare Ltd.": "METROPOLIS.NS",
//   "Minda Corporation Ltd.": "MINDACORP.NS",
//   "Motherson Sumi Wiring India Ltd.": "MSUMI.NS",
//   "Motilal Oswal Financial Services Ltd.": "MOTILALOFS.NS",
//   "MphasiS Ltd.": "MPHASIS.NS",
//   "Multi Commodity Exchange of India Ltd.": "MCX.NS",
//   "Muthoot Finance Ltd.": "MUTHOOTFIN.NS",
//   "NATCO Pharma Ltd.": "NATCOPHARM.NS",
//   "NBCC (India) Ltd.": "NBCC.NS",
//   "NCC Ltd.": "NCC.NS",
//   "NHPC Ltd.": "NHPC.NS",
//   "NLC India Ltd.": "NLCINDIA.NS",
//   "NMDC Ltd.": "NMDC.NS",
//   "NMDC Steel Ltd.": "NSLNISP.NS",
//   "NTPC Ltd.": "NTPC.NS",
//   "Narayana Hrudayalaya Ltd.": "NH.NS",
//   "National Aluminium Co. Ltd.": "NATIONALUM.NS",
//   "Navin Fluorine International Ltd.": "NAVINFLUOR.NS",
//   "Nestle India Ltd.": "NESTLEIND.NS",
//   "Netweb Technologies India Ltd.": "NETWEB.NS",
//   "Network18 Media & Investments Ltd.": "NETWORK18.NS",
//   "Newgen Software Technologies Ltd.": "NEWGEN.NS",
//   "Nippon Life India Asset Management Ltd.": "NAM-INDIA.NS",
//   "Nuvama Wealth Management Ltd.": "NUVAMA.NS",
//   "Nuvoco Vistas Corporation Ltd.": "NUVOCO.NS",
//   "Oberoi Realty Ltd.": "OBEROIRLTY.NS",
//   "Oil & Natural Gas Corporation Ltd.": "ONGC.NS",
//   "Oil India Ltd.": "OIL.NS",
//   "Olectra Greentech Ltd.": "OLECTRA.NS",
//   "One 97 Communications Ltd.": "PAYTM.NS",
//   "Oracle Financial Services Software Ltd.": "OFSS.NS",
//   "PB Fintech Ltd.": "POLICYBZR.NS",
//   "PCBL Chemical Ltd.": "PCBL.NS",
//   "PI Industries Ltd.": "PIIND.NS",
//   "PNB Housing Finance Ltd.": "PNBHOUSING.NS",
//   "PNC Infratech Ltd.": "PNCINFRA.NS",
//   "PTC Industries Ltd.": "PTCIL.NS",
//   "PVR INOX Ltd.": "PVRINOX.NS",
//   "Page Industries Ltd.": "PAGEIND.NS",
//   "Patanjali Foods Ltd.": "PATANJALI.NS",
//   "Persistent Systems Ltd.": "PERSISTENT.NS",
//   "Petronet LNG Ltd.": "PETRONET.NS",
//   "Pfizer Ltd.": "PFIZER.NS",
//   "Phoenix Mills Ltd.": "PHOENIXLTD.NS",
//   "Pidilite Industries Ltd.": "PIDILITIND.NS",
//   "Piramal Enterprises Ltd.": "PEL.NS",
//   "Piramal Pharma Ltd.": "PPLPHARMA.NS",
//   "Poly Medicure Ltd.": "POLYMED.NS",
//   "Polycab India Ltd.": "POLYCAB.NS",
//   "Poonawalla Fincorp Ltd.": "POONAWALLA.NS",
//   "Power Finance Corporation Ltd.": "PFC.NS",
//   "Power Grid Corporation of India Ltd.": "POWERGRID.NS",
//   "Praj Industries Ltd.": "PRAJIND.NS",
//   "Prestige Estates Projects Ltd.": "PRESTIGE.NS",
//   "Procter & Gamble Hygiene & Health Care Ltd.": "PGHH.NS",
//   "Punjab National Bank": "PNB.NS",
//   "Quess Corp Ltd.": "QUESS.NS",
//   "R R Kabel Ltd.": "RRKABEL.NS",
//   "RBL Bank Ltd.": "RBLBANK.NS",
//   "REC Ltd.": "RECLTD.NS",
//   "RHI MAGNESITA INDIA LTD.": "RHIM.NS",
//   "RITES Ltd.": "RITES.NS",
//   "Radico Khaitan Ltd": "RADICO.NS",
//   "Rail Vikas Nigam Ltd.": "RVNL.NS",
//   "Railtel Corporation Of India Ltd.": "RAILTEL.NS",
//   "Rainbow Childrens Medicare Ltd.": "RAINBOW.NS",
//   "Rajesh Exports Ltd.": "RAJESHEXPO.NS",
//   "Ramkrishna Forgings Ltd.": "RKFORGE.NS",
//   "Rashtriya Chemicals & Fertilizers Ltd.": "RCF.NS",
//   "Ratnamani Metals & Tubes Ltd.": "RATNAMANI.NS",
//   "RattanIndia Enterprises Ltd.": "RTNINDIA.NS",
//   "Raymond Ltd.": "RAYMOND.NS",
//   "Redington Ltd.": "REDINGTON.NS",
//   "Reliance Industries Ltd.": "RELIANCE.NS",
//   "Route Mobile Ltd.": "ROUTE.NS",
//   "SBFC Finance Ltd.": "SBFC.NS",
//   "SBI Cards and Payment Services Ltd.": "SBICARD.NS",
//   "SBI Life Insurance Company Ltd.": "SBILIFE.NS",
//   "SJVN Ltd.": "SJVN.NS",
//   "SKF India Ltd.": "SKFINDIA.NS",
//   "SRF Ltd.": "SRF.NS",
//   "Sammaan Capital Ltd.": "SAMMAANCAP.NS",
//   "Samvardhana Motherson International Ltd.": "MOTHERSON.NS",
//   "Sanofi India Ltd.": "SANOFI.NS",
//   "Sapphire Foods India Ltd.": "SAPPHIRE.NS",
//   "Saregama India Ltd": "SAREGAMA.NS",
//   "Schaeffler India Ltd.": "SCHAEFFLER.NS",
//   "Schneider Electric Infrastructure Ltd.": "SCHNEIDER.NS",
//   "Shipping Corporation of India Ltd.": "SCI.NS",
//   "Shree Cement Ltd.": "SHREECEM.NS",
//   "Shree Renuka Sugars Ltd.": "RENUKA.NS",
//   "Shriram Finance Ltd.": "SHRIRAMFIN.NS",
//   "Shyam Metalics and Energy Ltd.": "SHYAMMETL.NS",
//   "Siemens Ltd.": "SIEMENS.NS",
//   "Signatureglobal (India) Ltd.": "SIGNATURE.NS",
//   "Sobha Ltd.": "SOBHA.NS",
//   "Solar Industries India Ltd.": "SOLARINDS.NS",
//   "Sona BLW Precision Forgings Ltd.": "SONACOMS.NS",
//   "Sonata Software Ltd.": "SONATSOFTW.NS",
//   "Star Health and Allied Insurance Company Ltd.": "STARHEALTH.NS",
//   "State Bank of India": "SBIN.NS",
//   "Steel Authority of India Ltd.": "SAIL.NS",
//   "Sterling and Wilson Renewable Energy Ltd.": "SWSOLAR.NS",
//   "Sumitomo Chemical India Ltd.": "SUMICHEM.NS",
//   "Sun Pharma Advanced Research Company Ltd.": "SPARC.NS",
//   "Sun Pharmaceutical Industries Ltd.": "SUNPHARMA.NS",
//   "Sun TV Network Ltd.": "SUNTV.NS",
//   "Sundaram Finance Ltd.": "SUNDARMFIN.NS",
//   "Sundram Fasteners Ltd.": "SUNDRMFAST.NS",
//   "Supreme Industries Ltd.": "SUPREMEIND.NS",
//   "Suven Pharmaceuticals Ltd.": "SUVENPHAR.NS",
//   "Suzlon Energy Ltd.": "SUZLON.NS",
//   "Swan Energy Ltd.": "SWANENERGY.NS",
//   "Syngene International Ltd.": "SYNGENE.NS",
//   "Syrma SGS Technology Ltd.": "SYRMA.NS",
//   "TBO Tek Ltd.": "TBOTEK.NS",
//   "TVS Motor Company Ltd.": "TVSMOTOR.NS",
//   "TVS Supply Chain Solutions Ltd.": "TVSSCS.NS",
//   "Tanla Platforms Ltd.": "TANLA.NS",
//   "Tata Chemicals Ltd.": "TATACHEM.NS",
//   "Tata Communications Ltd.": "TATACOMM.NS",
//   "Tata Consultancy Services Ltd.": "TCS.NS",
//   "Tata Consumer Products Ltd.": "TATACONSUM.NS",
//   "Tata Elxsi Ltd.": "TATAELXSI.NS",
//   "Tata Investment Corporation Ltd.": "TATAINVEST.NS",
//   "Tata Motors Ltd.": "TATAMOTORS.NS",
//   "Tata Power Co. Ltd.": "TATAPOWER.NS",
//   "Tata Steel Ltd.": "TATASTEEL.NS",
//   "Tata Technologies Ltd.": "TATATECH.NS",
//   "Tata Teleservices (Maharashtra) Ltd.": "TTML.NS",
//   "Tech Mahindra Ltd.": "TECHM.NS",
//   "Techno Electric & Engineering Company Ltd.": "TECHNOE.NS",
//   "Tejas Networks Ltd.": "TEJASNET.NS",
//   "The New India Assurance Company Ltd.": "NIACL.NS",
//   "The Ramco Cements Ltd.": "RAMCOCEM.NS",
//   "Thermax Ltd.": "THERMAX.NS",
//   "Timken India Ltd.": "TIMKEN.NS",
//   "Titagarh Rail Systems Ltd.": "TITAGARH.NS",
//   "Titan Company Ltd.": "TITAN.NS",
//   "Torrent Pharmaceuticals Ltd.": "TORNTPHARM.NS",
//   "Torrent Power Ltd.": "TORNTPOWER.NS",
//   "Trent Ltd.": "TRENT.NS",
//   "Trident Ltd.": "TRIDENT.NS",
//   "Triveni Engineering & Industries Ltd.": "TRIVENI.NS",
//   "Triveni Turbine Ltd.": "TRITURBINE.NS",
//   "Tube Investments of India Ltd.": "TIINDIA.NS",
//   "UCO Bank": "UCOBANK.NS",
//   "UNO Minda Ltd.": "UNOMINDA.NS",
//   "UPL Ltd.": "UPL.NS",
//   "UTI Asset Management Company Ltd.": "UTIAMC.NS",
//   "Ujjivan Small Finance Bank Ltd.": "UJJIVANSFB.NS",
//   "UltraTech Cement Ltd.": "ULTRACEMCO.NS",
//   "Union Bank of India": "UNIONBANK.NS",
//   "United Breweries Ltd.": "UBL.NS",
//   "United Spirits Ltd.": "UNITDSPR.NS",
//   "Usha Martin Ltd.": "USHAMART.NS",
//   "V-Guard Industries Ltd.": "VGUARD.NS",
//   "V.I.P. Industries Ltd.": "VIPIND.NS",
//   "Valor Estate Ltd.": "DBREALTY.NS",
//   "Vardhman Textiles Ltd.": "VTL.NS",
//   "Varroc Engineering Ltd.": "VARROC.NS",
//   "Varun Beverages Ltd.": "VBL.NS",
//   "Vedant Fashions Ltd.": "MANYAVAR.NS",
//   "Vedanta Ltd.": "VEDL.NS",
//   "Vijaya Diagnostic Centre Ltd.": "VIJAYA.NS",
//   "Vinati Organics Ltd.": "VINATIORGA.NS",
//   "Vodafone Idea Ltd.": "IDEA.NS",
//   "Voltas Ltd.": "VOLTAS.NS",
//   "Welspun Corp Ltd.": "WELCORP.NS",
//   "Welspun Living Ltd.": "WELSPUNLIV.NS",
//   "Westlife Foodworld Ltd.": "WESTLIFE.NS",
//   "Whirlpool of India Ltd.": "WHIRLPOOL.NS",
//   "Wipro Ltd.": "WIPRO.NS",
//   "Yes Bank Ltd.": "YESBANK.NS",
//   "ZF Commercial Vehicle Control Systems India Ltd.": "ZFCVINDIA.NS",
//   "Zee Entertainment Enterprises Ltd.": "ZEEL.NS",
//   "Zensar Technolgies Ltd.": "ZENSARTECH.NS",
//   "Zomato Ltd.": "ZOMATO.NS",
//   "Zydus Lifesciences Ltd.": "ZYDUSLIFE.NS",
//   "eClerx Services Ltd.": "ECLERX.NS",
// };

const fetchAndStoreData = async () => {
  // Iterate over each index in the indices object
  for (const [name, symbol] of Object.entries(indices)) {
    // Fetch the index data using the fetchIndexData function
    const data = await fetchIndexData(symbol);

     // If data is missing, log an error and continue
     if (!data) {
      console.error(`Skipping ${name}: Data is missing`);
      continue;
    }

    // Use API's date if available, otherwise use today's date
     const dateToStore = data.date ? data.date : new Date().toISOString().split("T")[0];
 
     // Validate other fields
    if (!data.open || !data.high || !data.low || !data.current) {
      console.error(`Skipping ${name}: Some data fields are missing`, data);
      continue;
    }

    //check
    if (data) {
      console.log(`fetch data for ${name}`, data);
    }

    //query for store data into table
    await db.query(
      `INSERT INTO all_companies (index_name,date,open_price,high_price,low_price,current_price)
             VALUES (?,?,?,?,?,?)`,
      [name, dateToStore, data.open, data.high, data.low, data.current]
    );
  }
};

module.exports = { fetchAndStoreData, indices };
